### ISSUE TITLE
error with latest version of hugo

### ISSUE THREAD

**Issue by michaelsync** [mtn/athena-hugo-theme#3]
Your theme looks great but I got this error when I build with the latest hugo 

> Error: Error building site: failed to render pages: render of "home" failed: "C:\ms\ms-blx\themes\athena-hugo-theme\layouts\index.html:6:121": execute of template failed: template: index.html:25:13: executing "index.html" at <partial "post_block....>: error calling partial: "C:\ms\ms-blx\themes\athena-hugo-theme\layouts\partials\post_block.html:6:121": execute of template failed: template: partials/post_block.html:6:121: executing "partials/post_block.html" at <.Site.Params.datefor...>: invalid value; expected string

**Comment by mtn** [comment]
Thanks for reporting, I'll take a look later today.

**Comment by mtn** [comment]
@michaelsync Can't replicate on the example site with hugo version `0.55.6`, the latest available on homebrew. If you link me to your code I can try to help debug. It's also possible that there is a bug, but that the parameter settings on the example site don't trigger it.

**Comment by michaelsync** [comment]
You are right. 

I tried again with a new site. All good except this warrning .. So I guess it has something to do with my actual site. 

> WARN 2019/07/30 08:00:36 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like:
>     {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.


![image](https://user-images.githubusercontent.com/192911/62085978-4abe2e80-b2a0-11e9-83d1-95b3775af0f9.png)

**Comment by michaelsync** [comment]
Okie. I tried with my actual site and no more having an issue. Not sure what I did when I was getting that error. I was testing a lot of themes on that day. 

Thank you so much for your quick response. I appreciated it. 

![image](https://user-images.githubusercontent.com/192911/62086464-bbb21600-b2a1-11e9-996f-e433fad98a55.png)

**Comment by mtn** [comment]
Huh, at a glance that still looks somewhat strange to me. If you want to link me a site I can take a look.

**Comment by michaelsync** [comment]
Are you talking about the first screenshot (quickstart) or second one? 

For the first one, here is the steps to replicate. 

1. hugo new site quickstart
2. git clone your theme 
3. update the theme in config.
4. hugo new posts/my-first-post.md
5. hugo server -D

(You can see those steps in the first screenshot. Please ignore `echo theme => config` part. It didn't work on Windows. )

For second one, I added you as a collobrator. You will get the invite. Of course, you will need to change the config and theme.

**Comment by mtn** [comment]
Oh ok I see. You can get rid of the taxonomyTerm error by adding it to `disableKinds` in your config file. There's more explanation [here](https://github.com/mtn/cocoa-eh-hugo-theme/pull/114#issuecomment-480525858).

The RSS warning is a non-breaking issue that I'll fix soon.

**Comment by michaelsync** [comment]
All right. Great. Thanks, man.
